#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Thu Aug 15 21:11:48 2019

@author: vnit-stu
"""
def remove_dups(L1,L2):
    for e in L1:
        if e in L2:
            L1.remove(e)
    return L1

def remove_dups1(L1,L2):
    L1_copy =L1[:]
    for e in L1_copy:
        if e in L2:
            L1.remove(e)
    return L1

L1=[1,2,3,4]
L2=[1,2,5,6]
print(remove_dups(L1,L2))
print(remove_dups1(L1,L2))

